services:
  - type: web
    name: investment-dashboard-scraper
    env: node
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.x
    plan: free
