name: Update Prices
on:
  repository_dispatch:
    types: [update-prices]
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Run price updates
        id: update-prices
        run: |
          echo "::group::Running price updates"
          node server/scripts/scraper.js
          echo "::endgroup::"
          echo "update_status=completed" >> $GITHUB_OUTPUT
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          DEBUG: pw:api*

      - name: Update completion status
        if: always()
        run: |
          if [ "${{ steps.update-prices.outcome }}" == "success" ]; then
            echo "Price updates completed successfully"
          else
            echo "Price updates failed"
            exit 1
          fi
